apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstance
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: raniamoh-playground
  name: guest-book-frontend
spec:
  bootDisk:
    autoDelete: true
    deviceName: guest-book-frontend
    initializeParams:
      size: 10
      sourceImageRef:
        external: https://www.googleapis.com/compute/beta/projects/debian-cloud/global/images/debian-11-bullseye-v20230306
      type: pd-balanced
    mode: READ_WRITE
    sourceDiskRef:
      external: https://www.googleapis.com/compute/v1/projects/raniamoh-playground/zones/europe-west4-c/disks/guest-book-frontend
  confidentialInstanceConfig:
    enableConfidentialCompute: false
  machineType: e2-medium
  metadata:
  - key: enable-oslogin
    value: "true"
  networkInterface:
  - accessConfig:
      networkTier: PREMIUM
    name: nic0
    networkRef:
      external: https://www.googleapis.com/compute/v1/projects/raniamoh-playground/global/networks/openvpc
    stackType: IPV4_ONLY
    subnetworkProject: raniamoh-playground
    subnetworkRef:
      external: https://www.googleapis.com/compute/v1/projects/raniamoh-playground/regions/europe-west4/subnetworks/openvpc
  reservationAffinity:
    type: ANY_RESERVATION
  resourceID: guest-book-frontend
  scheduling:
    automaticRestart: true
    onHostMaintenance: MIGRATE
    provisioningModel: STANDARD
  serviceAccount:
    scopes:
    - https://www.googleapis.com/auth/service.management.readonly
    - https://www.googleapis.com/auth/servicecontrol
    - https://www.googleapis.com/auth/trace.append
    - https://www.googleapis.com/auth/devstorage.read_only
    - https://www.googleapis.com/auth/logging.write
    - https://www.googleapis.com/auth/monitoring.write
    serviceAccountRef:
      external: 189908348872-compute@developer.gserviceaccount.com
  shieldedInstanceConfig:
    enableIntegrityMonitoring: true
    enableVtpm: true
  tags:
  - http-server
  - https-server
  zone: europe-west4-c
